version: "3"

services:

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env.test
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/NIX-REST-API
    ports:
      - "5000:5000"
    depends_on:
      - db

  nginx:
      build:
        context: nginx/
        dockerfile: Dockerfile
      restart: always
      depends_on:
        - app
      ports:
        - "80:80"

volumes:
  postgres_data:

